public class Constants {
  public static final String INITIAL_ORDER_STATUS = 'Draft';
  public static final String ACTIVATED_ORDER_STATUS = 'Activated';
  public static final String NOPRODUCT_ERROR_MESSAGE = 'Please add at least one product before activating the order';
  public static final Integer UNIT_PRICE = 10;
  public static final Integer ITEM_QUANTITY = 10;
  public static final Integer NUM_RECORDS = 100;
}
